<div class="comment-block">
	<h3><?php echo $this->__('Comment')?></h3>
    <div  class="collapse-block">
		<form autocomplete="off">
			<div class="comment">
				<div class="comment-form">            
					<div class="input-box">	                
						<textarea class="input-text" id="customer_comment" name="customer_comment"></textarea>
					</div>	            
				</div>
			</div>
		</form>
	</div>
</div>
<div class="comment-block">
	<h3><?php echo $this->__('PO #')?><!--<span class='fa expand_plus'></span>--></h3>
    <div  class="collapse-block">
		<form autocomplete="off">
			<div class="comment">
				<div class="comment-form">            
					<div class="input-box">	                
						<input type="text" class="input-text" id="mmsg" name="mmsg">
					</div>	            
				</div>
			</div>
		</form>
	</div>
</div>
