<!--<script type="text/javascript" src="http://www.rearviewsafety.com/skin/frontend/default/rearviewsafety_updated/js/lib/elevatezoom/jquery.elevateZoom-3.0.8.min.js"></script>-->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/lib/elevatezoom/jquery.elevateZoom-3.0.8.min.js')?>"></script>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    
    $_lightboxConfig = Mage::getStoreConfig('easy_lightbox/general');
    /* Main Image Size */
    if (strstr($_lightboxConfig['mainImageSize'], '_')) {
        $mainImageSize = explode('_', $_lightboxConfig['mainImageSize'], 2);
    } else {
        $mainImageSize = array(265, 265);
    }
    /* Popup Image Size */
    if (strstr($_lightboxConfig['popupImageSize'], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig['popupImageSize'], 2);
    } else {
        $popupImageSize = array(0, 0);
    } 
    /* Additional Images Size */
    if (strstr($_lightboxConfig['additionalImageSize'], '_')) {
        $additionalImageSize = explode('_', $_lightboxConfig['additionalImageSize'], 2);
    } else {
        $additionalImageSize = array(60, 60);
    }
    
    $image = $this->helper('catalog/image')->init($_product, 'image');
    if ($popupImageSize[0] > 0) {
        $image = $this->helper('catalog/image')->init($_product, 'image')->resize($popupImageSize[0], $popupImageSize[1]);
    }
       
?>

<?php if(!$_lightboxConfig['defaulzoom']): ?>

<?php
	$maintitle = $this->htmlEscape($_product->getImageLabel());
	if( empty($maintitle) ):
	        $maintitle  = $_product->getName();
	endif;
?>
<div class="product-image product-image-zoom">
    <div class="product-image-gallery">
        <img id="image-main"
             class="gallery-image visible"
             src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />

        <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
            <?php if ($this->isGalleryImageVisible($_image)): ?>
            <img id="image-<?php echo $i; ?>"
                 class="gallery-image"
                 src="<?php echo $this->getGalleryImageUrl($_image); ?>"
                 data-zoom-image="<?php echo  $this->getGalleryImageUrl($_image); ?>" />
            <?php endif; ?>
        <?php $i++; endforeach; ?>
    </div>
</div>

<?php else: ?>

<p class="product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$maintitle.'" title="'.$maintitle.'" />';
        echo $_helper->productAttribute($_product, $_img, 'image')
    ?>
</p>
<p class="a-center" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>

<div class="image-zoom" id="track_outer">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
</script>

<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="img_thumb product-image-thumbs" style="height: 75px; overflow: hidden">
    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
        <?php if ($this->isGalleryImageVisible($_image)): ?>
        <div class="item">
            <a class="thumb-link" href="javascript:;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?php echo $i; ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(150); ?>"
                     width="75" height="75" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
            </a>
        </div>
        <?php endif; ?>
    <?php $i++; endforeach; ?>
    </div>

	
<?php endif; ?>


<script>
    jQuery(window).load(function(){
	jQuery(".img_thumb").css("height","auto");
	jQuery(".img_thumb").css("overflow","visible");
    });
    
    jQuery(".img_thumb").owlCarousel({
        items : 4,
	autoplay:false,
	loop : true,
        nav:true
        
	 });
    
    
</script>


