<script type="text/javascript" src="http://jwines.com/skin/frontend/default/jwines/js/jquery.js"></script>
				
					<script type="text/javascript" src="http://jwines.com/skin/frontend/default/jwines/js/jquery.lwtCountdown-1.0.js"></script>
				
<script type="text/javascript" src="<?php echo $this->getskinUrl('js/tooltip.js') ?>"></script>
					
<!-- Countdown dashboard start -->
		<div id="countdown_dashboard" class="ak12">
        <h1>Time Left to Buy</h1>
<!--			<div class="dash weeks_dash">
				<span class="dash_title">weeks</span>
				<div class="digit">0</div>
				<div class="digit">0</div>
			</div>-->

			<div class="dash days_dash">				
				<div class="digit">0</div>
				<div class="digit">0</div>
                <span class="dash_title">days</span>
			</div>

			<div class="dash hours_dash">
            	<div class="digit_wrapper">					
				<div class="digit first">0</div>
				<div class="digit">0</div>
                </div>
                <span class="dash_title">hours</span>
			</div>

			<div class="dash minutes_dash">
            <div class="digit_wrapper">				
				<div class="digit first">0</div>
				<div class="digit">0</div>
            </div>
            <span class="dash_title">minutes</span>
			</div>

			<div class="dash seconds_dash">	
            <div class="digit_wrapper">				
				<div class="digit first">0</div>
				<div class="digit">0</div>
             </div>   
             <span class="dash_title">seconds</span>   
			</div>

		
        
        <script language="javascript" type="text/javascript">
			jQuery(document).ready(function() {
				jQuery('#countdown_dashboard').countDown({
					targetDate: {
						'day': 		28,
						'month': 	08,
						'year': 	2012,
						'hour': 	0,
						'min': 		0,
						'sec': 		0
					},omitWeeks: true
				});
			});
		</script>
        </div>
		<!-- Countdown dashboard end -->
	