<div class="my-account">
    <div class="page-title">
        <h1>Recently Purchased Items</h1>
    </div>
    <form action="#" method="post" name="recent_cart_form" id="recent_cart_form" enctype="multipart/form-data">
        <table class="recent-buy">
            <?php 
            $helper = Mage::helper('catalog/product_configuration');
            $orders = Mage::getResourceModel('sales/order_collection')
            ->addFieldToSelect('*')
            ->addFieldToFilter('customer_id', Mage::getSingleton('customer/session')->getCustomer()->getId());
            //->addFieldToFilter('status', 'complete');
            $_orderCnt = $orders->count();
            //echo $_orderCnt;
            if($_orderCnt>0){
            ?>
                <thead>
                    <tr class="first">
                        <th class="recent-image"></th>
                        <th class="recent-name">PRODUCT NAME</th>
                        <th class="recent-price">PRICE</th>
                        <th class="recent-qunty">QUANTITY</th>
                        <th class="recent-addcart"></th>
                    </tr>
                </thead>
            <?php
            }else{
                echo "THERE IS NO ORDERED ITEM IN THIS ACCOUNT";
            }
            ?>
            <tbody class="recent-buy-tbd">
            <?php
            $this->setOrders($orders);
            foreach ($orders as $order){
                $order_id=$order->getRealOrderId();
                $order = Mage::getModel('sales/order')->load($order_id, 'increment_id');
                $order->getAllVisibleItems();
                $orderItems = $order->getItemsCollection()
                ->addAttributeToSelect('*')
                ->load();
                //echo "Order Total:".$order->getSubtotal();
                
                foreach($orderItems as $Items){
                    $Item = Mage::getModel('catalog/product')->setStoreId($Items->getStoreId())->load($Items->getProductId());
                    ?>
                    
                    <tr class="recent-details" id="recent-details-<?php echo $Item->getId()?>">
                        <td>
                            <a href="<?php echo $Item->getProductUrl(); ?>"><img src="<?php echo $Item->getImageUrl(); ?>" /></a>
                        </td>
                        <td>
                            <a href="<?php echo $Item->getProductUrl(); ?>"><?php echo $Item->getName(); ?></a>
                            <?php
                            $arr=array();
                            $arr1=array();
                            $options = $Items->getProductOptions(); 
                            $customOptions = $options['options'];   
                            if(!empty($customOptions)){
                                foreach ($customOptions as $option){ 
                                    $optionId = $option['option_id'];
                                    $optionvalId = $option['option_value'];
                                    echo '<input type="hidden" name="ordered-pro-id" value="'.$Item->getId().'" />';
                                    echo '<input type="hidden" name="data-optionid" value="'.$optionId.'" />';
                                    echo '<input type="hidden" name="data-optionvalid" value="'.$optionvalId.'" />';
                                    echo '<span class="option-name">'.$optionTitle = $option['label'].': '.'</span>';
                                    echo '<span class="option-value">'.$optionValue = $option['value'].'</span>'.'</br>';
                                    array_push($arr,$optionId);
                                    array_push($arr1,$optionvalId);
                                }
                            }
                            $arrComb = array_combine($arr,$arr1);
                            //echo "<pre>";
                            //print_r($arrComb);
                            //echo $params = json_encode($arrComb, JSON_PRETTY_PRINT);
                            ?>
                        </td>
                        <td>
                            <a href="<?php echo $Item->getProductUrl(); ?>"><?php echo "$".number_format($Items->getPrice(), '2'); ?></a> 
                        </td>
                        <td>
                            <?php echo '<input type="text" class="buy-qnty" name="buy-qnty" length="12" value="'. number_format($Items->getQtyOrdered(), '0').'" />';?>
                        </td>
                        <td>
                            <?php if(!$Item->canConfigure() && $Item->isSaleable()){ ?>
                                <a class="custom" href="<?php echo $this->getBaseUrl(); ?>checkout/cart/add/?product=<?php echo $Item->getId(); ?>&qty=<?php echo number_format($Items->getQtyOrdered(), '0');?>"><?php echo $this->__('Add To Cart'); ?></a>
                            <?php }else if($Item->canConfigure()){ ?>
                                <span class="opt-url" style="display: none;"><?php echo $this->getBaseUrl(); ?>checkout/cart/add/?product=<?php echo $Item->getId(); ?>&<?php echo http_build_query(array('options' => $arrComb))?>&qty=<?php echo number_format($Items->getQtyOrdered(), '0');?></span>
                                <a class="custom recent-addcart" href="<?php echo $this->getBaseUrl(); ?>checkout/cart/add/?product=<?php echo $Item->getId(); ?>&<?php echo http_build_query(array('options' => $arrComb))?>&qty=1"><?php echo $this->__('Add To Cart'); ?></a>
                            <?php }else{ ?>
                                <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php } ?>
                        </td>
                    </tr>
                    
                    <?php
                }
                ?>
                <?php
            }
            ?>   
            </tbody>
        </table>
    </form>
<?php
    if($_orderCnt>0){ ?>
        <a class="custom" href="<?php echo $this->getUrl('sales/order/history') ?>" style="float: right; margin-top:10px;"><?php echo $this->__('View All'); ?></a> 
    <?php
    }?>
</div>
<script type="text/javascript">
jQuery(document).ready(function($j){
    $j('.recent-buy-tbd .recent-details').each(function(){
        $j(this).children('td:nth-child(4)').find('input[name="buy-qnty"]').on('keyup',function(){
            var sendurl = $j(this).parent('td').next('td').children('a.custom').attr('href');
            sendurl = sendurl.split("qty=");
            var qty = sendurl[1];
            var newqty = $j(this).val();
            var newurl = sendurl[0]+"qty="+newqty;
            $j(this).parent('td').next('td').children('a.custom').attr('href',newurl);
        });
    });
});
</script>