<?php
/**
 * @category   Apptrian
 * @package    Apptrian_Subcategories
 * @author     Apptrian
 * @copyright  Copyright (c) 2015 Apptrian (http://www.apptrian.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$helper = Mage::helper('apptrian_subcategories');

$result = $helper->checkCategoryPage(
		preg_replace(array('/apptrian_subcategories_/', '/_after/', '/_before/'), array('', '', ''), $this->getNameInLayout()));

if (Mage::getStoreConfig('apptrian_subcategories/general/enabled')
	&& !$helper->isExcluded($result)
): ?>

<?php
    
	$pageType = $result['page_type'];
	
    $categories = $helper->getSubcategories($result);
    
    if (count($categories) > 0): ?>

<?php
    
    $layoutClass              = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/subcategories_layout');
    $showSubcategoriesHeading = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/show_subcategories_heading');
    $showCategoryName         = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/show_category_name');
    $showDescription          = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/show_description');
    $showImage                = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/show_image');
    $height                   = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/height');
    $width                    = Mage::getStoreConfig('apptrian_subcategories/' . $pageType . '/width');
    
    if ($height != '' || $width != '') {
    
        $placeholderImageUrl = Mage::getModel('catalog/product')->getSmallImageUrl($width, $height);
        
        $dAttribs = '';
        
        if ($height != '') {
            $dAttribs .= ' height="' . $height . '" ';
        }
        
        if ($width != '') {
            if ($dAttribs == '') {
                $dAttribs .= ' ';
            }
            $dAttribs .= 'width="' . $width . '" ';
        }
        
    } else {

        $placeholderImageUrl = Mage::getModel('catalog/product')->getSmallImageUrl();
        $dAttribs = ' ';
        
    }

    if ($showSubcategoriesHeading): ?>
<h2 class="apptrian-subcategories-heading" style="font-size:18px; color:#000000;"><?php echo $this->__('Subcategories') . ':'; ?></h2>
<style>
#catalog-listing{display:none;}
</style>
<?php endif;
    if ($layoutClass == 'layout-grid'): ?>
<ul class="apptrian-subcategories <?php echo 'apptrian-subcategories-' . $layoutClass; ?>">
    <?php foreach ($categories as $category): ?>
         <li style="width:225px; overflow:hidden; border:1px solid #666;">
            <?php
                // Get all needed data
                $href                = $category['url'];
                $categoryName        = $category['name'];
                $src                 = $helper->getImageUrl($category, $showImage, $placeholderImageUrl);
                $categoryDescription = $helper->getDescription($category, $showDescription);
            ?>
 <span style="height:225px;">
            <a href="<?php echo $href; ?>" class="product-image">
                <?php if ($showCategoryName == 'top'): ?>
                <span><?php echo $categoryName; ?></span>
                <?php endif; ?>
                <?php if ($showImage != 'none'): ?>
		
        <?php
		$new_file=explode("/",$src);
        $_file_name = $new_file[count($new_file)-1]; // Here $cat is category data array
		
	   
$_media_dir = Mage::getBaseDir('media') . DS . 'catalog' . DS . 'category' . DS;
 
 // Here i create a resize folder. for upload new category image
$cache_dir = $_media_dir . 'resize' . DS;
 
if (file_exists($cache_dir . $_file_name)) {
 
 $catImg =Mage::getBaseUrl('media') .  'catalog' . DS . 'category' . DS . 'resize' . DS . $_file_name;
 
} elseif (file_exists($_media_dir . $_file_name)) {
 
     if (!is_dir($cache_dir)) {
       mkdir($cache_dir);
    }
 
   $_image = new Varien_Image($_media_dir . $_file_name);
   $_image->constrainOnly(true);
   $_image->keepAspectRatio(true);
   $_image->keepFrame(true);
   $_image->keepTransparency(false);
   $_image->backgroundColor(array(255,255,255));
   $_image->resize(225, 225); // change image height, width
   $_image->save($cache_dir . $_file_name);
 
   $catImg = Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . 'resize' . DS . $_file_name;
 
}
 
 ?>

<img src="<?php echo $catImg;  ?>"  />
               </a>
</span>
                <?php endif; ?>
  <a href="<?php echo $href; ?>">
                <?php if ($showCategoryName == 'bottom'): ?>
                <span style="background-color:#575757; padding:1px; margin-top:9px; color:#ffffff; font-weight:bold;"><?php echo $categoryName; ?></span>
                <?php endif; ?>
            </a>
            <?php echo $categoryDescription; ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<ul class="apptrian-subcategories <?php echo 'apptrian-subcategories-' . $layoutClass; ?>">
    <?php foreach ($categories as $category): ?>
        <li style="width:232px; overflow:hidden; border:1px solid #666;">
            <?php
                // Get all needed data
                $href                = $category['url'];
                $categoryName        = $category['name'];
                $src                 = $helper->getImageUrl($category, $showImage, $placeholderImageUrl);
                $categoryDescription = $helper->getDescription($category, $showDescription);
            ?>
            <?php if ($showImage != 'none'): ?>
            <a href="<?php echo $href; ?>">
                <?php if ($showImage != 'none'): ?>
                <img src="/timthumb.php?src=<?php echo $src; ?>&h=210&w=140&zc=0" alt="<?php echo $categoryName; ?>"/>
                <?php endif; ?>
            </a>
            <div class="apptrian-subcategories-category-info">
            <?php endif; ?>
                <?php if ($showCategoryName == 'top'): ?>
                <h2 class="apptrian-subcategories-category-name"><a href="<?php echo $href; ?>"><?php echo $categoryName; ?></a></h2>
                <?php endif; ?>
                <?php echo $categoryDescription; ?>
                <?php if ($showCategoryName == 'bottom'): ?>
                <h2 class="apptrian-subcategories-category-name"><a href="<?php echo $href; ?>"><?php echo $categoryName; ?></a></h2>
                <?php endif; ?>
            <?php if ($showImage != 'none'): ?>
            </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php endif; ?>

<?php endif; ?>
          	<div class="whiteBox">
            	<div class="whiteBoxTop">
                	<h5>Janitorial</h5>
                    <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. </p>
                </div>
                <div class="proListBox">
                	<ul>
                    	<li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img1.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img2.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img3.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img4.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img1.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img1.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img2.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img3.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img4.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                        <li class="item">
                        	<a href="#" class="product-image"><img src="images/cate-img2.jpg" alt="sub-cate"></a>
                            <div class="product-info">
                            	<h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                                <p><a href="#">View Products</a></p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
