     <div class="content-header">
        <table cellspacing="0">
            <tr>
                <td>
                  <h3 class="icon-head"><?php echo $this->__('Picker Images') ?></h3>
                  <div style="float:right">
                    
                      <?php echo $this->getBlockHtml('formkey')?>  
		                  <button class="button" type="submit" onclick="$('pickerimages_form').submit();" ><span><span><?php echo $this->__('Save Images') ?></span></span></button>    
                    </form>
                  </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="entry-edit" >
      <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">&nbsp;</h4>
      </div>
      <div class="box">               
        <form id="pickerimages_form" action="<?php echo $this->getSaveUrl(); ?>" method="post">
          <?php echo $this->getBlockHtml('formkey')?>        
          <table class="ox-table" id="ox_table">
            <tr>
              <th width="200"><?php echo $this->__('Match option by title:'); ?></th>
              <th><?php echo $this->__('Image'); ?></th>    
            </tr>
            <?php foreach ($this->getValues() as $r): ?>
            <tr>
              <td>
                 <input type="text" id="ox_value_<?php echo $r['ox_image_id']; ?>_title" name="values[<?php echo $r['ox_image_id']; ?>][title]" value="<?php echo $r['title'];  ?>" />
              </td> 
              <td>
                <div class="no-display" id="ox_uploader_<?php echo $r['ox_image_id']; ?>-template">
                   <div id="{{id}}-container" class="file-row file-row-narrow">
                      <span class="file-info">
                         <span class="file-info-name">{{name}}</span>
                        
                         <span class="file-info-size">({{size}})</span>
                      </span>
                      <span class="progress-text"></span>
                      <div class="clear"></div>
                   </div>
                </div>
                <div class="files" style="width:135px;">
                   <span id="ox_uploader_<?php echo $r['ox_image_id']; ?>_place_holder" onmouseover="pickerImage.loadUploader(<?php echo $r['ox_image_id']; ?>)" <?php echo $r['image'] == '' ? '' : 'style="display:none"'; ?>><?php echo $this->__('Roll Over for Uploader'); ?></span>                                           
                   <div id="ox_uploader_<?php echo $r['ox_image_id']; ?>_row" class="hide_uploader_row">            
                      <div class="row" >
                      
                         <input type="hidden" id="ox_uploader_<?php echo $r['ox_image_id']; ?>_delete_image" name="values[<?php echo $r['ox_image_id']; ?>][delete_image]" value="" />                                
                         <input type="hidden" id="ox_uploader_<?php echo $r['ox_image_id']; ?>_saved_as" name="values[<?php echo $r['ox_image_id']; ?>][image_saved_as]" value="<?php echo $r['image']; ?>" />
                         <input type="hidden" id="ox_uploader_<?php echo $r['ox_image_id']; ?>_save" name="values[<?php echo $r['ox_image_id']; ?>][image]" value="" />                 

                         <div id="ox_uploader_<?php echo $r['ox_image_id']; ?>-browse" style="display:none">
                           <button id="ox_uploader_<?php echo $r['ox_image_id']; ?>-browse_button" title="<?php echo Mage::helper('uploader')->__('Browse Files...'); ?>" type="button" class="scalable browse" onclick="" style=""><span><span><span>...</span></span></span></button>
                           <input style="visibility: hidden; position: absolute;" type="file">
                         </div>                

                         <img src="<?php echo $r['image_url'];  ?>" id="ox_uploader_<?php echo $r['ox_image_id']; ?>_img" width="40" <?php echo $r['image'] != '' ? '' : 'style="display:none"'; ?>/><button id="ox_uploader_<?php echo $r['ox_image_id']; ?>-delete" title="<?php echo Mage::helper('adminhtml')->__('Delete Image'); ?>" type="button" class="scalable delete" onclick="pickerImage.deleteImage(<?php echo $r['ox_image_id']; ?>)" <?php echo $r['image'] != '' ? '' : 'style="display:none"'; ?>><span><span><span></span></span></span></button>                           

                         <div id="ox_uploader_<?php echo $r['ox_image_id']; ?>" class="uploader a-left">
                             <div id="ox_uploader_<?php echo $r['ox_image_id']; ?>-old" class="file-row-info"></div>
                             <div id="ox_uploader_<?php echo $r['ox_image_id']; ?>-new" class="file-row-info new-file"></div>
                             <div class="clear"></div>
                         </div> 

                      </div>
                   </div>
                </div>
              </td>                  
            </tr>                                                      
            <?php endforeach; ?> 
            <tr id="ox_add_image_row">
              <td colspan="2"><button class="scalable add ox-add-image" type="button" onclick="pickerImage.addRow()" ><span><span><?php echo $this->__('Add Image') ?></span></span></button></td>    
            </tr>            
          </table>        
        </form>
      </div>          
    </div> 



                                      
  <script type="text/javascript">
  //<![CDATA[ 
  
  PickerImage.Config = { 
     expiredMessage     : '<?php echo $this->jsQuoteEscape($this->__('Your session has been expired. Please, reload the page and upload images if necessary')) ?>',  
     uploaderConfig   : <?php echo $this->getConfigJson(); ?>,  
     uploaderId   : '<?php echo $this->getUploaderId(); ?>',     
     uploaderUrl : '<?php echo Mage::getBlockSingleton('adminhtml/media_uploader')->getUploaderUrl('media/uploaderSingle.swf'); ?>',
     
     row :  '<tr>'+
            '<td>'+
            ' <input type="text" id="ox_value_[[image_id]]_title" name="values[[[image_id]]][title]" value="" />'+
            '</td>'+ 
            '<td>'+                  
            '<div class="no-display" id="ox_uploader_[[image_id]]-template">'+
            '   <div id="{{id}}-container" class="file-row file-row-narrow">'+
            '      <span class="file-info">'+
            '         <span class="file-info-name">{{name}}</span>'+
            '         <span class="file-info-size">({{size}})</span>'+
            '      </span>'+
            '      <span class="progress-text"></span>'+
            '      <div class="clear"></div>'+
            '   </div>'+
            '</div>'+
            '<div class="files" style="width:135px;">'+
            '   <span id="ox_uploader_[[image_id]]_place_holder" onmouseover="pickerImage.loadUploader([[image_id]])"><?php echo $this->__('Roll Over for Uploader'); ?></span>'+      
            '   <div id="ox_uploader_[[image_id]]_row" class="hide_uploader_row">'+            
            '      <div class="row" >'+
            
                     '<input type="hidden" id="ox_uploader_[[image_id]]_delete_image" name="values[[[image_id]]][delete_image]" value="" />'+                                
                     '<input type="hidden" id="ox_uploader_[[image_id]]_saved_as" name="values[[[image_id]]][image_saved_as]" value="" />'+
                     '<input type="hidden" id="ox_uploader_[[image_id]]_save" name="values[[[image_id]]][image]" value="" />'+                 

                     '<div id="ox_uploader_[[image_id]]-browse" style="display:none">'+
                     '  <button id="ox_uploader_[[image_id]]-browse_button" title="<?php echo Mage::helper('uploader')->__('Browse Files...'); ?>" type="button" class="scalable browse"><span><span><span>...</span></span></span></button>'+
                     '  <input style="visibility: hidden; position: absolute;" type="file">'+
                     '</div>'+                

                     '<img src="" id="ox_uploader_[[image_id]]_img" width="40" style="display:none"/><button id="ox_uploader_[[image_id]]-delete" title="<?php echo Mage::helper('adminhtml')->__('Delete Image'); ?>" type="button" class="scalable delete" onclick="pickerImage.deleteImage([[image_id]])" style="display:none"><span><span><span></span></span></span></button>'+                           

                     '<div id="ox_uploader_[[image_id]]" class="uploader a-left">'+
                     '    <div id="ox_uploader_[[image_id]]-old" class="file-row-info"></div>'+
                     '    <div id="ox_uploader_[[image_id]]-new" class="file-row-info new-file"></div>'+
                     '    <div class="clear"></div>'+
                     '</div>'+             
                          
            '      </div>'+
            '   </div>'+
            '</div>'+
            '</td>'+
            '</tr>',
            
    lastImageId : <?php echo (int) $this->getLastImageId(); ?>                    

  };
  
  pickerImage = new PickerImage.Main();
   
  //]]> 
  </script>
