<?php
  /*
  * @copyright   Copyright ( c ) 2013 www.magebuzz.com
  */
  
if(Mage::getSingleton('customer/session')->isLoggedIn()) 
{
 
  $showPopupConfig = $this->_helper()->getConfigShowPopup();
  $hidePopupConfig = $this->_helper()->getConfigHidePopup();
  $cookieTime      = $this->_helper()->getConfigCookieTime(); 
  $listImage =$this->getListBannerpopup();
  if(count($listImage)>0){
    if($hidePopupConfig){
      if( Mage::getModel('core/cookie')->get('showimage') != 'true'){
        $randImage = $listImage[array_rand($listImage)];
        $this->_model()->addShowimage($randImage['id']);   
        Mage::getModel('core/cookie')->set('showimage', 'true', $cookieTime*24*60*60);
      }
    }else{
      $randImage = $listImage[array_rand($listImage)];
      $this->_model()->addShowimage($randImage['id']); 
    }
  }   
  $imgPath   = Mage::getBaseUrl('media')."bannerpopup/".$randImage['name'];
?>
<?php if($showPopupConfig):?>  
  <script type="text/javascript">  
	<?php if(count($listImage)>0):?>
    var $popup = jQuery.noConflict();
    <?php if($hidePopupConfig):?>   
      <?php if( Mage::getModel('core/cookie')->get('close_popup') != 'true'):?>
        $popup(document).ready(function() {
          $popup("#venture_spring_popup").fancybox({
            afterClose: function() {
              <?php Mage::getModel('core/cookie')->set('close_popup', 'true', $cookieTime*24*60*60);?>        
            }
          }).trigger('click');
        });
        <?php endif;?>
      <?php else:?>
      $popup(document).ready(function() {
        $popup("#venture_spring_popup").fancybox({          
        }).trigger('click');
      });
      <?php endif; ?>              
    function closePopup(){  
      jQuery.fancybox.close();
      var ajaxurl = "<?php echo Mage::getBaseUrl() . 'bannerpopup/index/addclick?id='.$randImage['id']?>";
      new Ajax.Request(ajaxurl, {
        method: 'Post',
        onSuccess: function(add_success_view) {      
          if(add_success_view.responseText !='false')
            {
            window.open(add_success_view.responseText,'_newtab');; 
          }          
        }
      });
    }
		<?php endif; ?>
  </script> 
  <a id="venture_spring_popup" style="display:none;" href="#bannerpopup-image"></a>
  <div id="bannerpopup-image" style="display: none;">
    <a onclick="return closePopup();">
      <img src="<?php echo $imgPath;?>" alt="<?php echo $randImage['title']?>">
    </a>
<?php //filtering the customers by email address
$customer = Mage::getSingleton('customer/session')->getCustomer();
$email = $customer->getEmail();
$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
$group = Mage::getModel('customer/group')->load($groupId);
$groupname = $group->getCode();
//echo $email;
  $orderCollection = Mage::getModel('sales/order')->getCollection()
					  ->addFieldToFilter('customer_email',$email);
  $total=0;
  
  foreach ($orderCollection as $_order): ?>
  <?php $order_total = $_order->getGrandTotal();
  //echo"<pre>";print_r($_order->getData());
  $total+=$order_total ;
   endforeach; ?>
  <?php if($total < '1500'){ 
  $subtotal=(1500-$total);?>
  <div style="font-size:22px; color:#FFFFFF; background:#c32228; margin:0px; border:#c32228 1px solid; text-align:center; text-transform:uppercase;  width:587px; padding-left:4px;">
  You have already spent $<?php echo number_format("$total",2); ?> on our site. When you spend an additional $<?php echo number_format("$subtotal",2);?> you will receive a $100 coupon off your next online order.
  </div>
  <?php } elseif($groupname == 'General'){
  $result=($total%1500);
  $subtotal=(1500-$result);
  //echo $result;?>
  <div style="font-size:22px; color:#FFFFFF; background:#c32228; margin:0px; border:#c32228 1px solid; text-align:center; text-transform:uppercase;  width:587px; padding-left:4px;">
  You have already spent $<?php echo number_format("$result",2); ?> on our site. When you spend an additional $<?php echo number_format("$subtotal",2);?> you will receive a $100 coupon off your next online order.
  </div>
  <?php
  }else{?>
  <div style="font-size:25px; color:#FFFFFF; background:#c32228; margin:0px; border:#c32228 1px solid; text-align:center; text-transform:uppercase;  width:587px; padding-left:4px;">
  You have already spent $<?php echo number_format("$total",2); ?> on our site.You have received a $100 coupon off on your order.
  </div>
<?php }
?>

</div>
  <?php endif; ?>
  
  <?php
}
  ?>
