<?php
/** 
 * @category Brainvire 
 * @package Brainvire_Ordercomment 
 * @copyright Copyright (c) 2015 Brainvire Infotech Pvt Ltd
 */ ?>
<?php $_order = $this->getOrder() ?>
<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<?php //echo $_order->getId() ?>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<div class="col2-set">
    
    
     <?php //$order = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId()); ?>
     
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Address') ?></h2>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="col-2">
    <?php else: ?>
    <div class="col-1">
    <?php endif; ?>
        <h2><?php echo $this->__('Billing Address') ?></h2>
	<?php $fnorder = Mage::getModel('sales/order')->load($_order->getId()); ?>
	<?php //If they have no customer id, they're a guest.
	if($fnorder->getCustomerId() === NULL){
	    echo "Facility Name: Not Found";
	} else {
	    //else, they're a normal registered user.
	    $customer = Mage::getModel('customer/customer')->load($fnorder->getCustomerId());
	    echo "Facility Name: ".$customer->getTaxvat();
	} ?>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
<?php if (!$_order->getIsVirtual()): ?>
</div>
<div class="col2-set">
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Method') ?></h2>
         <?php echo $_order->getShippingDescription() ?>
    </div>
<?php endif; ?>
    <div class="col-2">
        <h2><?php echo $this->__('Payment Method') ?></h2>
        <?php echo $this->getPaymentInfoHtml() ?>
    </div>
</div>

<div class="col2-set">
    <div class="col-1">
        <h2><?php echo $this->__('#PO') ?></h2>
        <?php echo $_order->getMmsg() ?>
	<?php
	//$_orderpo = Mage::getModel('sales/order')->load(5);
	//echo $_order->getMyorderPo();
	?>
    </div>
<?php if($_order->customer_note != "") { ?>
<!--<div style="clear:both; width:40%; margin-bottom:15px;">-->
    <div class="col-2">
	<div class="box-title"><h2><?php echo $this->__('Order Comments') ?></h2></div>
	<div class="box-content"><?php echo $_order->customer_note; ?></div>
    </div>
<?php } ?>
</div>

<h2><?php echo $this->__('Items Ordered') ?></h2>
<table class="data-table" id="my-orders-table">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?php echo $this->getChildHtml('order_totals') ?>
    </tfoot>
    <?php $_items = $_order->getItemsCollection(); ?>
    <?php $_count = $_items->count(); ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getParentItem()) continue; ?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
        <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<script type="text/javascript">window.print();</script>
