<?php
/** 
 * @category Brainvire 
 * @package Brainvire_Ordercomment 
 * @copyright Copyright (c) 2015 Brainvire Infotech Pvt Ltd
 */ ?>

<div class="order-items order-details">
    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('items', $this->getOrder())): ?>
    <script type="text/javascript">
    //<![CDATA[
    function giftMessageToogle(giftMessageIdentifier)
    {
        var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
        var container = $('order-item-gift-message-'+giftMessageIdentifier);
        var row = $('order-item-row-'+giftMessageIdentifier);
        if(link.expanded) {
            link.expanded = false;
            link.removeClassName('expanded');
            if(container.hasClassName('last')) {
                row.addClassName('last');
            }
            container.hide();
        } else {
            link.expanded = true;
            link.addClassName('expanded');
            if(container.hasClassName('last')) {
                row.removeClassName('last');
            }
            container.show();
        }

        return false;
    }
    //]]>
    </script>
    <?php endif; ?>
    <?php $_order = $this->getOrder() ?>
    
    
    <?php if($_order->customer_note != "") { ?>
    <div class="order-info-box" style="float:left; width:95%;">
		<div class="box">
			<div class="box-title"><h2><?php echo $this->__('Customer #PO') ?></h2></div>
                        
<form id="co-ordercomment-form" action="<?php echo $this->getUrl('ordercomment/index/update') ?>" method="post">
<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
<input type="hidden" name="order_id" value="<?php echo (int)$this->getRequest()->getParam('order_id'); ?>" />
<div class="buttons-set">
        <ul class="form-list">
            <li>
                <fieldset>
                    <ul>
                        <li class="wide">
                            <div class="input-box">
                            <input type="text" id="ordercomment" class="input-text" value="<?php echo $_order->customer_note; ?>" name="ordercomment" />
                               
                            </div>
                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </div>

                            <div class="button-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <div id="ordercomment-buttons-container">
        <button type="submit" class="button" ><span><span><?php echo $this->__('Update') ?></span></span></button>
    </div>
</div>
</form>

<script type="text/javascript">
//<![CDATA[
    var commentForm = new VarienForm('co-ordercomment-form', true);
//]]>
</script>

		</div>
	</div>
	<?php } ?>
	
	
    <h2 class="table-caption"><?php echo $this->__('Items Ordered') ?>
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <span class="separator">|</span> <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track your order') ?>"><?php echo $this->__('Track your order') ?></a>
        <?php endif; ?>
    </h2>
 
    <?php echo $this->getChildHtml('order_items') ?>

    <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="order-additional order-gift-message">
        <h2 class="sub-title"><?php echo $this->__('Gift Message for This Order') ?></h2>
        <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
        <dl class="gift-message">
            <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?></dt>
            <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?></dt>
            <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
        </dl>
    </div>
    <?php endif; ?>
    <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?php echo $this->__('About Your Order') ?></h2>
        <dl class="order-about">
            <?php foreach ($_history as $_historyItem): ?>
                <dt><?php echo $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?php echo $this->escapeHtml($_historyItem->getComment()) ?></dd>
            <?php endforeach; ?>
        </dl>
    </div>
    <?php endif; ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->getBackTitle() ?></a></p>
    </div>
</div>