<div class="bannerSec">
    <div id="fullSlider" class="owl-carousel owl-theme">
        <div class="item"><img src="<?php echo $this->getSkinUrl('images/banner.jpg')?>" width="846" height="470" alt="banner">
          <div class="banCap">You want it. <br>
            we have it.</div>
        </div>
        <div class="item"><img src="<?php echo $this->getSkinUrl('images/banner.jpg')?>" width="846" height="470" alt="banner">
          <div class="banCap">You want it. <br>
            we have it.</div>
        </div>
        <div class="item"><img src="<?php echo $this->getSkinUrl('images/banner.jpg')?>" width="846" height="470" alt="banner">
          <div class="banCap">You want it. <br>
            we have it.</div>
        </div>
        <div class="item"><img src="<?php echo $this->getSkinUrl('images/banner.jpg')?>" width="846" height="470" alt="banner">
          <div class="banCap">You want it. <br>
            we have it.</div>
        </div>
        <div class="item"><img src="<?php echo $this->getSkinUrl('images/banner.jpg')?>" width="846" height="470" alt="banner">
          <div class="banCap">You want it. <br>
            we have it.</div>
        </div>
    </div>
</div>
            <div class="tabWithSlider">
              <div class="tabList clearfix">
                <ul id="tabs">
                  <li class="active">on sale</li>
                  <li>featured items</li>
                  <li>clearance</li>
                  <li>high security</li>
                  <li>new</li>
                </ul>
              </div>
              <div class="tabContainer" id="tabContent">
                <div class="tabDetails active">
                  <div class="categoryList products-grid">
                    <div id="owlDemo1" class="owl-carousel">
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tabDetails">
                  <div class="categoryList products-grid">
                    <div id="owlDemo2" class="owl-carousel">
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tabDetails">
                  <div class="categoryList products-grid">
                    <div id="owlDemo3" class="owl-carousel">
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tabDetails">
                  <div class="categoryList products-grid">
                    <div id="owlDemo4" class="owl-carousel">
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tabDetails">
                  <div class="categoryList products-grid">
                    <div id="owlDemo5" class="owl-carousel">
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/cate-img1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          <div class="price-box" style="display:none;"> <span class="regular-price"> <span class="price">$2.00</span> </span> </div>
                          <div class="priceLogin">Log in to see prices</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="brandAdd clearfix">
            	<div class="brandItem"><a href="#"><img src="<?php echo $this->getSkinUrl('images/brand-add1.jpg')?>" alt="brand-add"></a></div>
                <div class="brandItem"><a href="#"><img src="<?php echo $this->getSkinUrl('images/brand-add2.jpg')?>" alt="brand-add"></a></div>
                <div class="brandItem"><a href="#"><img src="<?php echo $this->getSkinUrl('images/brand-add3.jpg')?>" alt="brand-add"></a></div>
            </div>
            <div class="allCategorySec">
            	<h4>all categories</h4>
                <div class="categoryList products-grid">
                    <div id="owlDemo6" class="owl-carousel">
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/all-acte1.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/all-acte2.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/all-acte3.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/all-acte4.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                          
                        </div>
                      </div>
                      <div class="item">
                        <div class="category-image"><a href="#"><img src="<?php echo $this->getSkinUrl('images/all-acte5.jpg')?>" alt="cate-img"></a></div>
                        <div class="product-info">
                          <h2 class="product-name"><a href="#">NEUTRAL FLOOR CLEANER</a></h2>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>

