<?php
/** 
 * @category Brainvire 
 * @package Brainvire_Ordercomment 
 * @copyright Copyright (c) 2015 Brainvire Infotech Pvt Ltd
 */ ?>

<form id="co-ordercomment-form" action="">
<div class="buttons-set">
        <ul class="form-list">
            <li>
                <fieldset>
                    <ul>
                        <li class="wide">
                            <label for="ordercomment">#PO</label>
                            <div class="input-box">
                            <input type="text" id="ordercomment" class="input-text validation-passed" name="ordercomment" />
                             
                            </div>
                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </div>
</form>

<div class="button-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <div id="ordercomment-buttons-container">
        <button type="button" class="button" onclick="ordercomment.save();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="ordercomment-please-wait" style="display:none;" class="opc-please-wait">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
        </span>
    </div>
</div>


<script type="text/javascript">
//<![CDATA[

var Ordercomment = Class.create();
Ordercomment.prototype = {
    initialize: function(form, saveUrl){
        this.form = form;
        if ($(this.form)) {
            $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
        }
        this.saveUrl = saveUrl;
        this.onSave = this.nextStep.bindAsEventListener(this);
        this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
    },

    save: function(){
        if (checkout.loadWaiting!=false) return;

        var validator = new Validation(this.form);
        if (validator.validate()) {

            checkout.setLoadWaiting('ordercomment');


            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    resetLoadWaiting: function(transport){
        checkout.setLoadWaiting(false);
    },

    nextStep: function(transport){
        if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
            if ((typeof response.message) == 'string') {
                alert(response.message);
            } else {
                if (window.billingRegionUpdater) {
                    billingRegionUpdater.update();
                }

                alert(response.message.join("\n"));
            }

            return false;
        }

        checkout.setStepResponse(response);
    }    
}

var ordercomment = new Ordercomment('co-ordercomment-form', '<?php echo $this->getUrl('checkout/onepage/saveOrdercomment') ?>');

//]]>
</script>