<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
?>
<tr>
    <td colspan="2">
        <div class="">
            <div id="css_preview_wrapper" class="layer_animation_preview_wrapper css_preview_wrapper">
                <div id="css_preview">Text</div>
            </div>
        </div>
    </td>
</tr>
<style type="text/css">
    table.form-list{
        width: 100%;
    }
</style>