<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td class="" style="width: 100%;padding-left: 5px">
        <table class="align_table" id="<?php echo $this->getElement()->getHtmlId()?>">
            <tr>
                <td><a href="#" data-id="1" data-hor="left" data-ver="top"></a></td>
                <td><a href="#" data-id="2" data-hor="center" data-ver="top"></a></td>
                <td><a href="#" data-id="3" data-hor="right" data-ver="top"></a></td>
            </tr>
            <tr>
                <td><a href="#" data-id="4" data-hor="left" data-ver="middle"></a></td>
                <td><a href="#" data-id="5" data-hor="center" data-ver="middle"></a></td>
                <td><a href="#" data-id="6" data-hor="right" data-ver="middle"></a></td>
            </tr>
            <tr>
                <td><a href="#" data-id="7" data-hor="left" data-ver="bottom"></a></td>
                <td><a href="#" data-id="8" data-hor="center" data-ver="bottom"></a></td>
                <td><a href="#" data-id="9" data-hor="right" data-ver="bottom"></a></td>
            </tr>
        </table>
    </td>
</tr>

<style>
    .align_table td{
        border: 1px solid #000;
        padding: 2px;
    }
    .align_table td a{
        text-decoration: none;
        display: block;
        width: 20px;
        height: 20px;
        background-color: #888;
        cursor: pointer;
    }
    .align_table td a.selected{
        background-color: #ED6502;
        cursor: default;
    }
    .align_table.disabled td{
        border: 1px solid #ACACAC;
    }
    .align_table.disabled td a{
        background-color: #ACACAC;
        cursor: default;
    }
</style>