<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
 
$element = $this->getElement();
$id = $element->getHtmlId();
?>
<tr>
    <td colspan="2">
        <div style="width: 100%">
            <textarea style="" id="<?php echo $id ?>"></textarea>
        </div>
    </td>
</tr>
