<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
?>
<tr>
    <td class="label"></td>
    <td class="value" style="">
        <?php echo $this->getChildHtml('edit')?>
        <?php echo $this->getChildHtml('new')?>
    </td>
</tr>