<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
 ?>
<tr>
    <td colspan=2>
        <?php if ($content = $this->getElement()->getData('content')):?>
        <div class="smdnsl-heading">
            <?php echo $content?>
        </div>
        <?php endif?>
    </td>
</tr>
