<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
?>
<tr>
    <td class="label"></td>
    <td class="value">
        <?php echo $this->getChildHtml('btn')?>
        <span style="display: none" id="videoLoading">
        <img style="vertical-align: middle" src="<?php echo $this->getSkinUrl()?>images/rule-ajax-loader.gif"/>
        </span>
    </td>
</tr>
