<?php
/**
 * @package SM Dynamic Slideshow 
 * @version 2.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @copyright Copyright (c) 2014 YouTech Company. All Rights Reserved.
 * @author YouTech Company http://www.magentech.com
 */
 
$element = $this->getElement();
$id = $element->getHtmlId();
?>
<tr>
    <td class="label">
        <?php echo $this->getElement()->getLabel()?>
    </td>
    <td class="value">
        <div id="<?php echo $id?>" class="css-slider"></div>
        <input type="hidden" name="<?php echo $id?>"/>
    </td>
</tr>
<script type="text/javascript">
    jQuery('#<?php echo $id?>').slider({
        range: 'min',
        min: <?php echo $element->getData('min')?>,
        max: <?php echo $element->getData('max')?>,
        <?php if ($element->getData('step')):?>
        step: <?php echo $element->getData('step')?>,
        <?php endif ?>
        slide: function(e,u){
            jQuery(u.handle).text(u.value);
            jQuery('input[name="<?php echo $id?>"]').val(u.value + 'px');
        },
        change: function(e,u){
            jQuery(u.handle).text(u.value);
            jQuery('input[name="<?php echo $id?>"]').val(u.value + 'px');
        }
    }).slider('option', 'value', <?php echo $element->getData('value') ? $element->getData('value') : $element->getData('min')?>);
</script>